version: "3.9"
services:

  social_network:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["bash", "./start.sh"]
    restart: always
    env_file:
      - parameters.env

  db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  db-test:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:latest


volumes:
  postgres_data: