version: "3.9"
services:

  social_network:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["bash", "./start.sh"]
    restart: always
    environment:
      - DB_HOST=db
      - TEST_DB_HOST=db-test
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_PORT=5432
      - DB_DRIVER=postgresql
      - DB_NAME=postgres
      - DB_TEST_NAME=postgres
      - SECRET_KEY=1a7e9bc3b68f4d65b91ef21d1672b5a2f7cdd29d1bce4fb0a0a7e2a4c9e5fcdb
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10
      - ENRICHMENT_API_KEY=12345
      - ENRICHMENT_URL=https://person.clearbit.com/v2/combined/find?email=
      - HUNTER_API_KEY=
      - HUNTER_URL=https://api.hunter.io/v2/email-verifier
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_ENCODING=utf-8

  db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  db-test:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:latest


volumes:
  postgres_data: