"""added enrichment data

Revision ID: 212c3fe01e16
Revises: c4ecac1e8857
Create Date: 2023-07-05 11:22:37.826492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212c3fe01e16'
down_revision = 'c4ecac1e8857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enrichment_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('given_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('family_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'enrichment_id')
    # ### end Alembic commands ###
