"""added unique constraint to email user field

Revision ID: 821d2693b130
Revises: 7bbf9a1e45bd
Create Date: 2023-07-04 21:51:59.137365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821d2693b130'
down_revision = '7bbf9a1e45bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
