"""added the direction to likes

Revision ID: c4ecac1e8857
Revises: d81db9cc1c03
Create Date: 2023-07-05 02:42:39.895485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ecac1e8857'
down_revision = 'd81db9cc1c03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('direction', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'direction')
    # ### end Alembic commands ###
