"""fixed relationships

Revision ID: d81db9cc1c03
Revises: 821d2693b130
Create Date: 2023-07-04 22:05:23.325168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81db9cc1c03'
down_revision = '821d2693b130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
